### PR TITLE
Make Python3 compatible, add test, fill in missing params

### PR DESCRIPTION
**Pull request by allenluce**
Tested with Python 2.7 and Python 3.3.  Could use more coverage...

### CODE REVIEW

**Comment by muhuk** [comment]
Hi @allenluce 

Thanks for the PR. There are a few minor issues I noted. I'll merge once they're fixed.

**Comment by allenluce** [comment]
Sounds good, please check out the latest commit.

**Comment by muhuk** [comment]
I am going ahead and merging this.

I am confused about the MAX_CATEGORY_LISTINGS_COUNT thing though.

If you agree that MAX_CATEGORY_LISTINGS_COUNT should just be 100 and make another PR for it, please add yourself to the AUTHORS file as well.

Thanks again for the contrib.

**Comment by allenluce** [comment]
No worries, I commented on the commit about MAX_CATEGORY_LISTINGS_COUNT.  Thanks for merging!

**Pull request merged**
